version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: maptheaccused-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: maptheaccused
    volumes:
      - mongodb_data:/data/db
    networks:
      - maptheaccused-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: maptheaccused-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/maptheaccused
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - maptheaccused-network
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: maptheaccused-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - maptheaccused-network
    env_file:
      - ./frontend/.env

volumes:
  mongodb_data:
    driver: local

networks:
  maptheaccused-network:
    driver: bridge